name: "Run Cypress tests"
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    container: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter nextjs...

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          command: pnpm --filter nextjs cypress
          browser: chrome
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          SKIP_ENV_VALIDATION: 1
