name: "Run Cypress tests"
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: |
            - args: [--filter nextjs...]

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          command: pnpm --filter nextjs cypress
          install: false
          browser: chrome
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          SKIP_ENV_VALIDATION: 1
